/**
 * A trimmed copy of illumineertales.com's cards.json (the official reveal list, issue #574),
 * as it stood on 2026-09-24. Each entry is here for a shape that has caused a mistake:
 *
 *   #1, #144  unrevealed slots, which still carry an ink
 *   #14       a Japanese first reveal, with a translation link
 *   #44, #106 accents the site's image filenames keep ("he-ctor")
 *   #60       an official set card whose rarity reads PROMO
 *   #73       renamed after its reveal; its scan file keeps the old name, and it has no
 *             translation link although the scan is French
 *   #91       lorcanaplayer has the wrong version ("Great Stomper")
 *   #152      a curly apostrophe
 *   #182      an official card whose rarity is still blank
 *   #213      a revealed slot above the main set
 *
 * #150 is invented, to match the TEST_INVENTOR page fixture. The list is trimmed, so Tramp
 * (set #122 on the real list) appears only as a promo here.
 */

const REVEALED_BY = {reveal_timestamp: '2026-09-23T12:00:00.000Z', revealed_by: 'Test Source'};

export const OFFICIAL_JSON = {
  'set-14-hyperia-city': [
    {
      set_number: 1,
      name: '',
      subtitle: '',
      magic_ink_colors: ['AMBER'],
      card_type: '',
      rarity: '',
      keywords: [],
      image_version: '',
      translation_url: '',
      reveal_timestamp: '',
      revealed_by: '',
      revealed_url: '',
    },
    {
      set_number: 14,
      name: 'Nick Wilde',
      subtitle: 'Toy Donation Coordinator',
      magic_ink_colors: ['AMBER'],
      card_type: 'CHARACTER',
      rarity: 'SUPER_RARE',
      keywords: ['Zootopia'],
      image_version: '',
      translation_url: 'https://www.instagram.com/p/DdmVcbYjrc0/?img_index=3',
      reveal_timestamp: '2026-09-23T11:00:00.000Z',
      revealed_by: 'Disney Lorcana JP',
      revealed_url: 'https://www.youtube.com/watch?v=sAMdt1ASUQk',
    },
    {
      set_number: 44,
      name: 'Mamá Coco',
      subtitle: 'Visiting the Park',
      magic_ink_colors: ['AMETHYST'],
      card_type: 'CHARACTER',
      rarity: 'RARE',
      keywords: ['Coco'],
      image_version: 'press',
      translation_url: '',
      reveal_timestamp: '2026-09-22T17:00:00.000Z',
      revealed_by: 'Special Lorecast',
      revealed_url: 'https://www.twitch.tv/videos/2881130109',
    },
    {
      set_number: 60,
      name: 'Everyone Knows Juanita',
      subtitle: null,
      magic_ink_colors: ['AMETHYST'],
      card_type: 'ACTION',
      rarity: 'PROMO',
      keywords: ['Coco'],
      image_version: 'app',
      translation_url: '',
      reveal_timestamp: '2026-09-23T11:00:00.000Z',
      revealed_by: 'Disney Lorcana JP',
      revealed_url: 'https://www.youtube.com/watch?v=sAMdt1ASUQk',
    },
    {
      set_number: 73,
      name: 'Molly Cunningham',
      subtitle: 'Remember to Share',
      magic_ink_colors: ['EMERALD'],
      card_type: 'CHARACTER',
      rarity: 'UNCOMMON',
      keywords: ['TaleSpin'],
      image_version: 'app',
      translation_url: '',
      reveal_timestamp: '2026-09-23T10:00:00.000Z',
      revealed_by: 'Val & PL',
      revealed_url: 'https://www.twitch.tv/val_pl_magicarenafr',
    },
    {
      set_number: 91,
      name: 'Fred',
      subtitle: 'Big Stomper',
      magic_ink_colors: ['EMERALD'],
      card_type: 'CHARACTER',
      rarity: 'COMMON',
      keywords: ['Big Hero 6'],
      image_version: 'app',
      translation_url: '',
      reveal_timestamp: '2026-09-23T11:08:00.000Z',
      revealed_by: 'lorcanalab',
      revealed_url: 'https://www.instagram.com/lorcanalab/reel/DdoHl9iIK61/',
    },
    {
      set_number: 106,
      name: 'Héctor Rivera',
      subtitle: 'Worldwide Sensation',
      magic_ink_colors: ['RUBY'],
      card_type: 'CHARACTER',
      rarity: 'LEGENDARY',
      keywords: ['Coco'],
      image_version: '',
      translation_url: '',
      reveal_timestamp: '2026-09-22T18:15:00.000Z',
      revealed_by: 'Screenrant',
      revealed_url:
        'https://screenrant.com/disney-lorcana-hyperia-city-new-cards-reveal-exclusive/',
    },
    {
      set_number: 118,
      name: 'Ernesto de la Cruz',
      subtitle: 'Idol of Millions',
      magic_ink_colors: ['RUBY'],
      card_type: 'CHARACTER',
      rarity: 'COMMON',
      keywords: ['Coco'],
      image_version: '',
      translation_url: '',
      reveal_timestamp: '2026-09-22T18:15:00.000Z',
      revealed_by: 'Screenrant',
      revealed_url:
        'https://screenrant.com/disney-lorcana-hyperia-city-new-cards-reveal-exclusive/',
    },
    {
      set_number: 144,
      name: '',
      subtitle: '',
      magic_ink_colors: ['SAPPHIRE'],
      card_type: '',
      rarity: '',
      keywords: [],
      image_version: '',
      translation_url: '',
      reveal_timestamp: '',
      revealed_by: '',
      revealed_url: '',
    },
    {
      set_number: 147,
      name: 'Lionheart',
      subtitle: 'Cleaning Up the City',
      magic_ink_colors: ['SAPPHIRE'],
      card_type: 'CHARACTER',
      rarity: 'UNCOMMON',
      keywords: ['Zootopia'],
      image_version: 'app',
      translation_url: '',
      reveal_timestamp: '2026-09-23T13:15:00.000Z',
      revealed_by: 'Zatu Games',
      revealed_url: 'https://zatu.com/blogs/news/disney-lorcana-hyperia-city-zatu-card-reveal',
    },
    {
      set_number: 150,
      name: 'Test Inventor',
      subtitle: 'Gadget Tinkerer',
      magic_ink_colors: ['SAPPHIRE'],
      card_type: 'CHARACTER',
      rarity: 'UNCOMMON',
      keywords: [],
      image_version: '',
      translation_url: '',
      ...REVEALED_BY,
      revealed_url: 'https://example.test/reveal',
    },
    {
      set_number: 152,
      name: 'Thomas O’Malley',
      subtitle: 'Savvy Vagabond',
      magic_ink_colors: ['SAPPHIRE'],
      card_type: 'CHARACTER',
      rarity: 'SUPER_RARE',
      keywords: ['The Aristocats'],
      image_version: 'app',
      translation_url: '',
      reveal_timestamp: '2026-09-22T08:45:00.000Z',
      revealed_by: 'Disney Lorcana App',
      revealed_url: 'https://cards.disneylorcana.com/en-US/',
    },
    {
      set_number: 182,
      name: 'Toulouse',
      subtitle: 'Rough and Tumble',
      magic_ink_colors: ['STEEL'],
      card_type: 'CHARACTER',
      rarity: '',
      keywords: ['The Aristocats'],
      image_version: 'app',
      translation_url: '',
      reveal_timestamp: '2026-09-22T17:00:00.000Z',
      revealed_by: 'Special Lorecast',
      revealed_url: 'https://www.twitch.tv/videos/2881130109',
    },
    {
      set_number: 213,
      name: 'Baymax',
      subtitle: 'Lab Assistant',
      magic_ink_colors: ['EMERALD'],
      card_type: 'CHARACTER',
      rarity: 'EPIC',
      keywords: ['Big Hero 6'],
      image_version: 'press',
      translation_url: 'https://www.instagram.com/p/DdnzS5mDe8d/?img_index=1',
      reveal_timestamp: '2026-09-23T07:00:00.000Z',
      revealed_by: 'Disney Lorcana',
      revealed_url: 'https://disneylorcana.com/en-US/',
    },
  ],
  promos: [
    {
      promo_set: 'RPH',
      set_number: 1,
      name: 'Everyone Knows Juanita',
      subtitle: '',
      magic_ink_colors: ['AMETHYST'],
      card_type: 'ACTION',
      rarity: 'PROMO',
      keywords: ['Coco'],
      image_version: 'press',
      translation_url: '',
      reveal_timestamp: '2026-09-22T17:00:00.000Z',
      revealed_by: 'Special Lorecast',
      revealed_url: 'https://www.twitch.tv/videos/2881130109',
    },
    {
      promo_set: 'RPH',
      set_number: 2,
      name: 'Tramp',
      subtitle: 'Quick on His Feet',
      magic_ink_colors: ['RUBY'],
      card_type: 'CHARACTER',
      rarity: 'PROMO',
      keywords: ['Lady and the Tramp'],
      image_version: 'press',
      translation_url: '',
      reveal_timestamp: '2026-09-22T17:00:00.000Z',
      revealed_by: 'Special Lorecast',
      revealed_url: 'https://www.twitch.tv/videos/2881130109',
    },
  ],
};

/** The season the official list is read for, shaped like web.mjs's loadSeason(). */
export const SEASON14 = {
  setCode: '14',
  setNumber: 14,
  setName: 'Hyperia City',
  setSlug: 'hyperia-city',
  setTotal: 204,
};
